spring.application.name=assessment

spring.jpa.open-in-view=false
spring.datasource.url=jdbc:h2:file:./data/mydb;MODE=PostgreSQL;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

job.batch-size=100
job.max-retries=3